## Columns to convert to numeric if they are not already
```{r}
library(dplyr)
print("Original type:")
str(data)

data <- data %>%
  mutate(
    Age = as.numeric(Age),
    Num_of_Delayed_Payment = as.numeric(Num_of_Delayed_Payment),
    Changed_Credit_Limit = as.numeric(Changed_Credit_Limit),
    Outstanding_Debt = as.numeric(Outstanding_Debt),
    Amount_invested_monthly = as.numeric(Amount_invested_monthly),
    Annual_Income = as.numeric(as.character(Annual_Income)),
    Monthly_Inhand_Salary = as.numeric(as.character(Monthly_Inhand_Salary)),
    Num_Bank_Accounts = as.numeric(Num_Bank_Accounts),
    Num_Credit_Card = as.numeric(Num_Credit_Card),
    Interest_Rate = as.numeric(Interest_Rate),
    Num_of_Loan = as.numeric(Num_of_Loan),
    Delay_from_due_date = as.numeric(Delay_from_due_date),
    Num_Credit_Inquiries = as.numeric(Num_Credit_Inquiries),
    Credit_Utilization_Ratio = as.numeric(Credit_Utilization_Ratio),
    Total_EMI_per_month = as.numeric(Total_EMI_per_month),
    Monthly_Balance = as.numeric(Monthly_Balance)
  ) 

print("type after conversion:")
str(data)
    
```
## Calculate the percentage of missing values for each column

```{r}
data <- data %>%
  mutate(across(c(Annual_Income, Monthly_Inhand_Salary, Num_Bank_Accounts, Num_Credit_Card,
                  Interest_Rate, Num_of_Loan, Delay_from_due_date, Num_of_Delayed_Payment,
                  Changed_Credit_Limit, Num_Credit_Inquiries, Outstanding_Debt, 
                  Credit_Utilization_Ratio, Credit_History_Age, Total_EMI_per_month, 
                  Amount_invested_monthly, Monthly_Balance), 
                ~na_if(., "_") %>%
                  na_if(., "NA") %>%
                  na_if(., "") %>%
                  na_if(., "na")))

# 
missing_values_ratio <- data %>%
  summarise(across(c(Annual_Income, Monthly_Inhand_Salary, Num_Bank_Accounts, Num_Credit_Card,
                     Interest_Rate, Num_of_Loan, Delay_from_due_date, Num_of_Delayed_Payment,
                     Changed_Credit_Limit, Num_Credit_Inquiries, Outstanding_Debt, 
                     Credit_Utilization_Ratio, Credit_History_Age, Total_EMI_per_month, 
                     Amount_invested_monthly, Monthly_Balance), 
                   ~sum(is.na(.)) / n()))
print(missing_values_ratio)
```

## View the distribution of columns
```{r}
library(ggplot2)

columns <- c("Age", "Annual_Income", "Monthly_Inhand_Salary", "Num_Bank_Accounts", "Num_Credit_Card", "Num_of_Loan")

par(mfrow = c(3, 2))

for (column_name in columns) {
  graph <- ggplot(data, aes_string(y = column_name)) +
    geom_boxplot(fill = "lightblue", color = "black") +
    theme_minimal() +
    labs(title = paste("Boxplot of", column_name), y = column_name) +
    theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(), plot.title = element_text(hjust = 0.5)) 
  
  print(graph) 
}
```

